### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by laurence702** [LaravelDaily/Hotel-Booking#14]
Very wonderful Job Sir. 

But The entire project keeps translating to Spanish in the browser by default until I have to click the translate button. But I've looked in the views and I've seen its written in english. what could be a fix for this please

**Comment by PovilasKorop** [comment]
@laurence702 no idea, to be honest, it could be your browser issue. We haven't seen anything like that while doing our testing.

**Comment by izzatilbe** [comment]
@laurence702 I also have the same issue! Fixed it by changing /config/app.php 
change `'locale' => 'es'` to `'locale' => 'en'`

**Comment by PovilasKorop** [comment]
@izzatilbe thanks for pointing it out, fixed in the repository. No idea how we left Spanish as the first locale, we never planned to do that, maybe typo.

**Comment by laurence702** [comment]
Thank you @PovilasKorop for this wonderful repo. made me learn how to use some of Laravels great features. 
and thanks @izzatilbe for pointing that out. it works fine
