### ISSUE TITLE
After instalation

### ISSUE THREAD

**Issue by tibioltean** [LaravelDaily/Hotel-Booking#2]
http://localhost/hotel-booking/public/login

Sorry, the page you are looking for could not be found.

XAMPP for Windows 7.2.2

**Comment by PovilasKorop** [comment]
@tibioltean probably because your domain and `/public` folder isn't configured properly?
I work with Homestead and create domains for every project, so I don't need to have `/public` in URLs. So check your configuration, please.

**Comment by tibioltean** [comment]
Thanks, 
I rename the Hotel-Booking folder to booking  in htdocs and and it works
