### ISSUE TITLE
Unable to Create New Model!

### ISSUE THREAD

**Issue by vignesh-subash** [LaravelDaily/Hotel-Booking#3]
i am trying to implement some new features and unable to show the newly created Module in the sidebar.

**Comment by PovilasKorop** [comment]
@vignesh-subash so what exactly is unclear? It's Laravel code, so not sure how can I help you - explain something in the Laravel code?

**Comment by vignesh-subash** [comment]
Sorry about previous communication.

I am trying to create to filed called states in the application. i created Model, Controller, View, Route and DB config. Even i made the changes in @lang section also. But the State Field is not visible in the Application Dashboard.
![screen shot 2018-03-21 at 12 18 51](https://user-images.githubusercontent.com/13498070/37697292-10121fd2-2d02-11e8-8c5f-d2ff598275ba.png)
![screen shot 2018-03-21 at 12 19 58](https://user-images.githubusercontent.com/13498070/37697310-33750908-2d02-11e8-969c-141814584730.png)

**Comment by PovilasKorop** [comment]
@vignesh-subash ok thanks now I can understand the problem. I guess it's somewhere in `sidebar.blade.php` file, menu items are listed there. Also check the permissions - the blocks there are protected with **@can** operator so make sure the user has the permissions.

You can show me `sidebar.blade.php` screenshot, and then I could comment/help more, maybe.

**Comment by vignesh-subash** [comment]
@PovilasKorop Thanks for the quick reply, i made the changes in the sidebar.blade.php as well. Here are the codes!

`@inject('request', 'Illuminate\Http\Request')

<aside class="main-sidebar">
    
    <section class="sidebar">
        <ul class="sidebar-menu">



            <li class="{{ $request->segment(1) == 'home' ? 'active' : '' }}">
                <a href="{{ url('/') }}">
                    <i class="fa fa-wrench"></i>
                    <span class="title">@lang('quickadmin.qa_dashboard')</span>
                </a>
            </li>


            @can('user_management_access')
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span class="title">@lang('quickadmin.user-management.title')</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                @can('role_access')
                <li class="{{ $request->segment(2) == 'roles' ? 'active active-sub' : '' }}">
                        <a href="{{ route('admin.roles.index') }}">
                            <i class="fa fa-briefcase"></i>
                            <span class="title">
                                @lang('quickadmin.roles.title')
                            </span>
                        </a>
                    </li>
                @endcan
                @can('user_access')
                <li class="{{ $request->segment(2) == 'users' ? 'active active-sub' : '' }}">
                        <a href="{{ route('admin.users.index') }}">
                            <i class="fa fa-user"></i>
                            <span class="title">
                                @lang('quickadmin.users.title')
                            </span>
                        </a>
                    </li>
                @endcan
                </ul>
            </li>
            @endcan
            @can('country_access')
            <li class="{{ $request->segment(2) == 'countries' ? 'active' : '' }}">
                <a href="{{ route('admin.countries.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.countries.title')</span>
                </a>
            </li>
            @endcan

            @can('state_access')
            <li class="{{ $request->segment(2) == 'states' ? 'active' : '' }}">
                <a href="{{ route('admin.states.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.states.title')</span>
                </a>
            </li>
            @endcan


            @can('customer_access')
            <li class="{{ $request->segment(2) == 'customers' ? 'active' : '' }}">
                <a href="{{ route('admin.customers.index') }}">
                    <i class="fa fa-low-vision"></i>
                    <span class="title">@lang('quickadmin.customers.title')</span>
                </a>
            </li>
            @endcan

            @can('room_access')
            <li class="{{ $request->segment(2) == 'rooms' ? 'active' : '' }}">
                <a href="{{ route('admin.rooms.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.rooms.title')</span>
                </a>
            </li>
            @endcan

            @can('booking_access')
            <li class="{{ $request->segment(2) == 'bookings' ? 'active' : '' }}">
                <a href="{{ route('admin.bookings.index') }}">
                    <i class="fa fa-bell"></i>
                    <span class="title">@lang('quickadmin.bookings.title')</span>
                </a>
            </li>
            @endcan

            @can('find_room_access')
            <li class="{{ $request->segment(2) == 'find_rooms' ? 'active' : '' }}">
                <a href="{{ route('admin.find_rooms.index') }}">
                    <i class="fa fa-arrows"></i>
                    <span class="title">@lang('quickadmin.find-room.title')</span>
                </a>
            </li>
            @endcan








            <li class="{{ $request->segment(1) == 'change_password' ? 'active' : '' }}">
                <a href="{{ route('auth.change_password') }}">
                    <i class="fa fa-key"></i>
                    <span class="title">@lang('quickadmin.qa_change_password')</span>
                </a>
            </li>

            <li>
                <a href="#logout" onclick="$('#logout').submit();">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">@lang('quickadmin.qa_logout')</span>
                </a>
            </li>
        </ul>
    </section>
</aside>
`

**Comment by PovilasKorop** [comment]
@vignesh-subash ok and your `state_access` permission is set up properly? 
All permissions are set in `AuthServiceProvider` here: https://github.com/LaravelDaily/Hotel-Booking/blob/master/app/Providers/AuthServiceProvider.php

**Comment by vignesh-subash** [comment]
@PovilasKorop Thank you so much! Its my silly mistake! How come i missed that!! i like to integrate your laravel-invoice into this project and hope it added few more features. Can i share the codes once i complete the few add-ons!?

**Comment by PovilasKorop** [comment]
@vignesh-subash sure but not sure how much time I have to look/help, my time is really limited
