### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by wailynnoo** [LaravelDaily/Hotel-Booking#4]
When i run the project i got the 404 page with error message.
"Sorry, the page you are looking for could not be found."
How should i fix?
Thanks!

**Comment by PovilasKorop** [comment]
@wailynnoo maybe you misconfigured something? What is actually the page that is not loading? Homepage? Could you give the exact URL, maybe you've set your `/public` folder wrong, or something like that.

**Comment by lungu-catalin** [comment]
Hi. I have the same problem.
This is the url:
http://localhost/hotel-booking/public/admin/home

**Comment by wailynnoo** [comment]
I solve this problem by running "php artisan serve" command

**Comment by clowdeyy** [comment]
what credentials would I have to put in .env file?

**Comment by jhonyjain** [comment]
what credentials would I have to put in .env file?

**Comment by jhonyjain** [comment]
what credentials would I have to put in login form ?

**Comment by PovilasKorop** [comment]
@jhonyjain see Readme file, section "How to use"

**Comment by arunk9034** [comment]
How to run without php artisan serve
