### ISSUE TITLE
Error in : php artisan migrate --seed

### ISSUE THREAD

**Issue by Jbarlian** [LaravelDaily/Hotel-Booking#5]
I came across this error when I try to seed it.

In Connection.php line 664:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQL: insert into `users` (`id`, `name`, `emai  
  l`, `password`, `role_id`, `remember_token`, `updated_at`, `created_at`) values (1, Admin, admin@admin.com, $2y$10$akHCvTRpvma2eB8VOqUEoOt  
  pWEelS2/e2TZK3LJyfLxuvw8MrQxVq, 1, , 2019-03-09 12:23:48, 2019-03-09 12:23:48)) 

In PDOStatement.php line 107:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

In PDOStatement.php line 105:
 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'  

Any suggestions would be greatly appreciated.

**Comment by PovilasKorop** [comment]
@Jbarlian it means your database isn't empty, that there is already user with ID 1

**Comment by Jbarlian** [comment]
@PovilasKorop Thank you I think this should solve the issue.
